# Generated by Django 3.1.4 on 2021-01-12 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0005_auto_20210112_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredits',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercredits', to=settings.AUTH_USER_MODEL),
        ),
    ]
