# Generated by Django 3.1.4 on 2021-01-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20210113_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredits',
            name='credits',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='usercredits',
            name='key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
